### ISSUE TITLE
support ifelse

### ISSUE THREAD

**Issue by mlubin** [JackDunnNZ/AmplNLWriter.jl#1]
Would it be difficult to support ``ifelse``, i.e., 
```
ifelse(condition, expression_if_true, expression_if_false)
```
Just ran into a model that I wanted to test out the .nl writer with but it has some ``ifelse`` statements.

**Comment by mlubin** [comment]
Actually in this model the ``condition`` just depends on input data, so all that would be needed is to simplify the expression.

**Comment by JackDunnNZ** [comment]
The excel version handles both cases so this shouldn't be a problem to
bring over

**Comment by JackDunnNZ** [comment]
Do you have a model handy I can use for implementing and testing this?

**Comment by mlubin** [comment]
https://github.com/JuliaOpt/JuMP.jl/commit/c45bbb6acf60f7926c4795f6b8616379f10a5461

**Comment by mlubin** [comment]
That's with a variable expression in the condition.

**Comment by JackDunnNZ** [comment]
Both cases should now be working, in the second objective, the `ifelse` is reduced to `x^2` before writing to the .nl file as expected. Only caveat is that comparisons in the `ifelse` can't be more than 3 terms eg. `1 <= x <= 3` won't work

    m = Model(solver=nlp_solver)
    @defVar(m, x, start = 2)
    # minimizer at smooth point, solvers should be okay
    @setNLObjective(m, Min, ifelse( x <= 1, x^2, x) )
    status = solve(m)

    @fact status => :Optimal
    @fact getValue(x) => roughly(0.0, 1e-5)

    # Now try with a constant expression
    @setNLObjective(m, Min, ifelse( 0 <= 1, x^2, x) )
    status = solve(m)
    @fact status => :Optimal
    @fact getValue(x) => roughly(0.0, 1e-5)

**Comment by mlubin** [comment]
Cool!

**Comment by JackDunnNZ** [comment]
Now chained comparisons are working e.g all of the following:

    @setNLObjective(m, Min, ifelse( -1 <= x <= 1, x^2, abs(x)) )
    @setNLObjective(m, Min, ifelse( -1 <= 0 <= 1, x^2, x) )
    @setNLObjective(m, Min, ifelse( -1 <= x <= y <= 1, x^2 + y^2, abs(x) + abs(y)) )
