### ISSUE TITLE
The lower case `l` really bugs me

### ISSUE THREAD

**Issue by IainNZ** [JackDunnNZ/AmplNLWriter.jl#3]
in the name, its impossible to read in sans-serif fonts. What to do you think about a rename?

(complaining about names is such a productive use of time :D)

**Comment by mlubin** [comment]
Ref https://github.com/dpo/ampl.jl/issues/6

**Comment by JackDunnNZ** [comment]
Agree completely. I'll blame it on copy pasting the wrong one from the thread Miles linked :)

**Comment by mlubin** [comment]
CC @tkelman @dpo
I'm also in favor of upper case ``NL``.

**Comment by JackDunnNZ** [comment]
Uppercase L is back, much relief was experienced by all

**Comment by tkelman** [comment]
Yeah I think I prefer `AmplNLWriter` over `AmplNlWriter` over `AMPLNLWriter`

**Comment by dpo** [comment]
I'm happy with `NL`.
