### ISSUE TITLE
[PkgEval] AmplNLWriter may have a testing issue on Julia 0.3 (2015-05-17)

### ISSUE THREAD

**Issue by IainNZ** [JackDunnNZ/AmplNLWriter.jl#4]
[PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) is a script that runs nightly. It attempts to load all Julia packages and run their tests (if available) on both the stable version of Julia (0.3) and the nightly build of the unstable version (0.4). The results of this script are used to generate a [package listing](http://pkg.julialang.org/) enhanced with testing results.

#### On Julia 0.3
* On **2015-05-17** the testing status was `N/A - new package.`
* On **2015-05-17** the testing status changed to `Package doesn't load.`

`Package doesn't load.` means that PackageEvaluator did not find tests for your package. Additionally, trying to load your package with `using` failed.

*This issue was filed because your testing status became worse. No additional issues will be filed if your package remains in this state, and no issue will be filed if it improves. If you'd like to opt-out of these status-change messages, reply to this message saying you'd like to and @IainNZ will add an exception. If you'd like to discuss [PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) please file an issue at the repository. For example, your package may be untestable on the test machine due to a dependency - an exception can be added.*

*Test log*:
```
>>> 'Pkg.add("AmplNLWriter")' log
INFO: Cloning cache of AmplNLWriter from git://github.com/JackDunnNZ/AmplNLWriter.jl.git
INFO: Cloning cache of MathProgBase from git://github.com/JuliaOpt/MathProgBase.jl.git
INFO: Installing AmplNLWriter v0.0.1
INFO: Installing Compat v0.4.4
INFO: Installing MathProgBase v0.3.11
INFO: Package database updated

>>> 'using AmplNLWriter' log
Julia Version 0.3.6
Commit 0c24dca (2015-02-17 22:12 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
/home/vagrant/testpkg/v0.3/AmplNLWriter

ERROR: AmplNLWriter not found
 in require at loading.jl:47
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading /vagrant/releaseAL/PKGEVAL_AmplNLWriter_using.jl, in expression starting on line 4

>>> test log
no tests to run
>>> end of log
```

**Comment by IainNZ** [comment]
Is this because the filename for the main src file has a lower-case `l`?

**Comment by mlubin** [comment]
Looks like it. It wouldn't be caught on OS X because it's case insensitive.

**Comment by IainNZ** [comment]
Setting up Travis probably a good idea before JuliaOpt-ing it

**Comment by JackDunnNZ** [comment]
Whoops should be fixed now

**Comment by tkelman** [comment]
I'll write a julia-users post about this later, but I figured out how to use the Docker workers on Travis (`sudo: false`) to cache dependencies, which cut down my build times from 15 minutes to 2 minutes for CoinOptServices. You might want to borrow my yml: https://github.com/JuliaOpt/CoinOptServices.jl/blob/8d7e2495d948fd8623a6a6c3d6d17ac9069a9a2e/.travis.yml

**Comment by JackDunnNZ** [comment]
Travis is up now
