### ISSUE TITLE
IpoptNLSolver returns infeasible solution with status :Optimal

### ISSUE THREAD

**Issue by odow** [JackDunnNZ/AmplNLWriter.jl#6]
I attempted to solve a non-linear model using `Ipopt.jl`, `IpoptNLSolver` and `BonminNLSolver` (I have `CoinOptServices` installed).

`Ipopt.jl` and `BonminNLSolver` return nearly identical solutions that appear to be local optima. 

However, `IpoptNLSolver` returns an infeasible solution, but with the status `Ipopt 3.12.2: Optimal Solution Found`.

I used AmplNLWriter to create a nl file, and then passed it to the ipopt and bonmin executables. The offending .nl and .sol files can be found in the following gist. 
https://gist.github.com/odow/18bff3fb0a4601d1353f

I am hesitant to post the Julia model publicly. I'll try tomorrow to trim down a minimal example, but a lot of things interconnect.

I guess the first thing is working out if
 - The .nl file is not being created correctly @JackDunnNZ 
 - There is a bug in the Ipopt executable @tkelman

**Comment by mlubin** [comment]
It's a nonconvex model, so also important to check that the starting point is getting passed correctly to Ipopt.

**Comment by odow** [comment]
These are the correct starting values (the ones that are zero I have explicitly set to their lower bounds)
https://gist.github.com/odow/18bff3fb0a4601d1353f#file-model-nl-L18220-L18587

**Comment by tkelman** [comment]
What's your Julia `versioninfo` (mostly, what platform is this)?

Maybe worth looking at what `OsilSolver` or `OsilBonminSolver` do on the same problem, if you can't share the Julia code then at least the osil representation of the same problem would be another thing to look at.

**Comment by odow** [comment]
Julia Version 0.3.9
Commit 31efe69 (2015-05-30 11:24 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

Latest AmplNLWriter
Latest JuMP
CoinOptServices v0.0.5
Ipopt v0.1.15

Ipopt.exe v3.12.2
Bonmin.exe v1.8.1, using Cbc 2.9.2 and Ipopt 3.12.2

**Comment by odow** [comment]
I've updated the gist with the Osil files. They (OsilSolver and OsilBonminSolver) both seem to work (i.e. find the same solution as Ipopt.jl and Bonmin).

I should say that I think its outstanding work that its possible to interchange between solvers so easily.

**Comment by JackDunnNZ** [comment]
@odow Is it possible for you to email me a copy of the JuMP model so that I can work through the .nl file and compare to the real model?

**Comment by odow** [comment]
Sent to your aucklanduni email

**Comment by JackDunnNZ** [comment]
Thanks, I'll try have a look later today

**Comment by odow** [comment]
Since this appears to be solving alright via Bonmin etc its not urgent. Its more of interest why Ipopt via the NL file borks but pretends everything is okay.

**Comment by mlubin** [comment]
Was there any resolution here?

**Comment by JackDunnNZ** [comment]
I haven't got around to looking into it yet. Together with this issue (https://github.com/JuliaOpt/JuMP.jl/issues/474) and the fact that `Ipopt.jl`, `OsilSolver`, `OsilBonminSolver` and `BonminNLSolver` all manage to solve correctly, it looks like there might be a problem with how Ipopt is reading the .nl files, but not sure if the problem is on my end writing them or their end reading them.

I could try forming the problem from the linked issue in AMPL and using AMPL to write the .nl file and see if the issues persist. If not, it's my writing of the file that's the problem, and I'll be able to compare to the AMPL version to see where I am off.

**Comment by JackDunnNZ** [comment]
@odow I finally got around to sorting this out, are you able to try it out? Sorry for the crazy delay

**Comment by odow** [comment]
I'll have a look today. Been AWOL for a while

**Comment by odow** [comment]
So. Pulling the lastest master from both AmplNLWriter and CoinOptServices. on v0.4rc-2

For the original model I sent you, they now all converge to the same solution so whatever that problem was has been fixed!

However, when I tested them all on the latest version of my model:
`Ipopt.jl` converges to a solution that is feasible, and a local optimum.
`BonminNLSolver` and `IpoptNLSolver` both converge to essentially the same solution and return `Optimal` but the solution is infeasible (clear violation of an inequality constraint).

The constraint they are violating is actually linear. However, I added it using `@addNLConstraint` since it contains a `NLExpr` (even though the expression is actually linear).

When I explicitly write out the constraint using `@addConstraint` everything solves correctly. 

Trying to find a simple reproducible case now.

```
Julia Version 0.4.0-rc2
Commit fa52609* (2015-09-18 17:51 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
```
14 required packages:
 - AmplNLWriter                  0.0.2+             master
 - Cairo                         0.2.31
 - Cbc                           0.1.7
 - CoinOptServices               0.0.6+             master
 - DataFrames                    0.6.9
 - DataFramesMeta                0.0.1
 - Dates                         0.4.4
 - Formatting                    0.1.4
 - GLM                           0.4.7
 - Gadfly                        0.3.16
 - Gurobi                        0.1.29
 - JuMP                          0.10.1
 - NLopt                         0.2.2
 - PyPlot                        2.1.0
53 additional packages:
 - ArrayViews                    0.6.4
 - BinDeps                       0.3.17
 - Calculus                      0.1.10
 - Clp                           0.0.10
 - Codecs                        0.1.4
 - ColorTypes                    0.1.5
 - Colors                        0.5.4
 - Compat                        0.7.3
 - Compose                       0.3.15
 - Contour                       0.0.7
 - DataArrays                    0.2.18
 - DataStructures                0.3.13
 - Distances                     0.2.0
 - Distributions                 0.8.6
 - Docile                        0.5.19
 - DualNumbers                   0.1.3
 - FactCheck                     0.4.0
 - FixedPointNumbers             0.0.11
 - GZip                          0.2.18
 - Graphics                      0.1.3
 - Grid                          0.3.11
 - Hexagons                      0.0.4
 - HttpCommon                    0.2.3
 - HttpParser                    0.1.0
 - ImmutableArrays               0.0.10
 - Ipopt                         0.1.16
 - Iterators                     0.1.9
 - JSON                          0.4.6
 - KernelDensity                 0.1.1
 - LaTeXStrings                  0.1.4
 - LibExpat                      0.0.8
 - LightXML                      0.2.0
 - Loess                         0.0.4
 - MathProgBase                  0.3.17
 - MbedTLS                       0.1.3
 - NEOS                          0.0.0-             develop (unregistered, dirty)
 - NaNMath                       0.1.0
 - NumericFuns                   0.2.3
 - Optim                         0.4.2
 - PDMats                        0.3.5
 - PyCall                        1.0.2
 - Reexport                      0.0.3
 - Requests                      0.3.1
 - ReverseDiffSparse             0.2.10
 - SHA                           0.1.2
 - Showoff                       0.0.5
 - SortingAlgorithms             0.0.6
 - StatsBase                     0.7.2
 - StatsFuns                     0.1.3
 - URIParser                     0.1.0
 - WinRPM                        0.1.12
 - WoodburyMatrices              0.1.2
 - Zlib                          0.1.9
```

**Comment by odow** [comment]
I should confirm. That with the constraint written explicitly, both `Ipopt.jl` and `IpoptNLSolver` take identical numbers of iterations and function/gradient evaluations, converge to identical solutions! So this is a bug in AmplNLWriter. Somewhere.

**Comment by odow** [comment]
Here are the two .NL files and a diff of them https://gist.github.com/odow/b1ddae7ef9e8fd48cc2f

**Comment by JackDunnNZ** [comment]
Thanks for looking into this. The diff in the files is mostly noise from one of the constraints shifting order in the problem, but it looks like some of the coeffs on the linear variables are changing as well as the bounds on those constraints. If you can send it through I'll take a look. I tried a local example with an `@defNLExpr` but that worked, so the bug isn't quite that simple.

**Comment by odow** [comment]
Sent the code to your aucklanduni email

**Comment by JackDunnNZ** [comment]
I think the issue is with `@addConstraint` vs `@addNLConstraint`. If I define `xLW` with `@defExpr` rather than `@defNLExpr` and change the constraint to `@addConstraint`, everything works fine even with the expression. Need to figure out what is going wrong when the constraint is added with `@addNLConstraint`

**Comment by odow** [comment]
I can't seem to reproduce this in a simpler example...

**Comment by JackDunnNZ** [comment]
If you make the following change, does it break?

    make_it_work = true
    if make_it_work
                # This constraint will work
                @addConstraint(...

to

    make_it_work = true
    if make_it_work
                # This constraint will work
                @addNLConstraint(...

All it is is changing the working `@addConstraint` to `@addNLConstraint`. For me it breaks things, which helps remove the question of whether the `NLExpr` is complicating things

**Comment by odow** [comment]
I'm sure I tried this and it worked earlier. But now it breaks.

So its some problem with adding a `NLConstraint` that is actually linear?

**Comment by JackDunnNZ** [comment]
Apparently. I have other examples where it works fine, but they are simple. I'll dig down and figure out where it is going wrong.

The difference is that JuMP simplifies the constraint as much as possible before passing to MPB using @addConstraint, but when it is done with @addNLConstraint it passes through the original expression tree without simplification, so I must be simplifying part of it incorrectly.

**Comment by odow** [comment]
Found it! https://gist.github.com/odow/32bb5cde5c94f60d4886

**Comment by JackDunnNZ** [comment]
Thanks, that was it! Can you try with latest master? The linear simplification was presuming only binary multiplication operations since n-ary is meant to be filtered out, but that filtering only occurs on the non-linear parts of the constraint. It should now be n-ary aware, and both the simple problem and original problem of yours should work! I've also added a test case for it to be sure

**Comment by odow** [comment]
Awesome. Ill give it a go. I was delving into the depths of `nl_linearity.jl` and getting a bit confused.

**Comment by odow** [comment]
Does this mean there is a problem with division as well?

**Comment by JackDunnNZ** [comment]
I think division shouldn't ever be showing up as n-ary, but I could be wrong. @mlubin do you know?

**Comment by mlubin** [comment]
I don't know how the julia parser would produce n-ary division.

**Comment by odow** [comment]
Success! I think this can officially be closed.

**Comment by JackDunnNZ** [comment]
Great! Thanks again for your help in figuring out where the issue was.
