### ISSUE TITLE
Implement linear interface

### ISSUE THREAD

**Issue by JackDunnNZ** [JackDunnNZ/AmplNLWriter.jl#9]

**Comment by JackDunnNZ** [comment]
Just added the linear interface, using Bonmin seems to pass JuMP's linear tests (other than the checks for duals).

**Comment by mlubin** [comment]
Anyone up for trying to call scip through this?

**Comment by JackDunnNZ** [comment]
If it's not much work to get a scip binary I can try...

**Comment by mlubin** [comment]
It's not too bad

**Comment by mlubin** [comment]
CC @fserra @ryanjoneil

**Comment by JackDunnNZ** [comment]
The homepage lists a Windows binary with AMPL support at the bottom of the
list, maybe I'll try that first :)

**Comment by JackDunnNZ** [comment]
Okay, so I followed Victor's instructions [here](http://zverovich.net/2012/08/07/using-scip-with-ampl.html) to build the scipampl binary, and it's working on the tests. I just need to tidy up a few assumptions about how to run the solvers since scipampl uses different flags to the coin solvers

**Comment by JackDunnNZ** [comment]
@mlubin It should work if you want to try it. You'll need to follow the instructions in the link before to build `scipampl` and then use it with:

    AmplNLSolver("/path/to/scipampl")

I had to change the way we invoke solve commands since SCIP just reads the model file as the first arg, but the coin solvers read it from the -s flag.

Other than not currently giving duals, it's passing the LP/MILP tests in JuMP

**Comment by mlubin** [comment]
Confirmed that scip is passing MILP tests

**Comment by mlubin** [comment]
Could you tag a new release including this?

**Comment by JackDunnNZ** [comment]
I'd like to get #16 finished up to make sure we are reading the .sol file correctly, but after that I'll tag a new release

**Comment by JackDunnNZ** [comment]
@mlubin Just tagged and opened the PR
